name: Download artifact
description: Wrapper around GitHub's official action, with additional extraction before download

# https://github.com/actions/download-artifact/blob/main/action.yml
inputs:
  name:
    description: Artifact name
    required: true
  path:
    description: Destination path
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Download artifacts
      if: github.event_name != 'workflow_run'
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.name }}
        path: ${{ inputs.path }}
        merge-multiple: true

    - name: Download artifacts
      if: github.event_name == 'workflow_run'
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: ${{ github.event.workflow_run.name }}
        run_id: ${{ github.event.workflow_run.id }}
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}

    - name: Extract artifacts
      run: |
        for t in ${{ inputs.name }}*.tar
        do
          tar -xvf "${t}"
        done
      shell: bash
      working-directory: ${{ inputs.path }}

    - name: Remove archive
      run: rm -f ${{ inputs.name }}*.tar
      shell: bash
      working-directory: ${{ inputs.path }}
